### ISSUE TITLE
Advanced Config Error:

### ISSUE THREAD

**Issue by winterfellhard** [Armarr/Autorank-2#135]
http://forums.bukkit.org/threads/autorank-issue.316660/

Everything was working fine with the basic config. I decided to implement my advanced config and I am now getting an error. Not sure how you want it posted so I placed it on the forums and link it here. 

Thanks for any help! Love the features!

[CODE]
Loading libraries, please wait...
[04:44:33 INFO]: Starting minecraft server version 1.7.9
[04:44:33 INFO]: Loading properties
[04:44:34 INFO]: Default game type: SURVIVAL
[04:44:34 INFO]: Generating keypair
[04:44:34 INFO]: Starting Minecraft server on *:25565
[04:44:34 INFO]: This server is running CraftBukkit version git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks (MC: 1.7.9) (Implementing API version 1.7.9-R0.2)
[04:44:36 WARN]: Could not get information about this CraftBukkit version; perhaps you are running a custom one?: IOException
[04:44:36 INFO]: [mcore] Loading mcore v7.2.1
[04:44:36 INFO]: [WorldEdit] Loading WorldEdit v5.6.2
[04:44:36 INFO]: [Essentials] Loading Essentials v2.13.1
[04:44:36 INFO]: [PermissionsBukkit] Loading PermissionsBukkit v2.4
[04:44:36 INFO]: [EssentialsChat] Loading EssentialsChat v2.13.1
[04:44:36 INFO]: [Craftconomy3] Loading Craftconomy3 v3.1.6 jenkins-Craftconomy3-2149
[04:44:36 INFO]: [jCommands] Loading jCommands v2.0.2
[04:44:36 INFO]: [mcMMO] Loading mcMMO v1.5.00-b3547
[04:44:36 INFO]: [CustomJoinItems] Loading CustomJoinItems v1.5.1
[04:44:36 INFO]: [Vault] Loading Vault v1.4.1-b436
[04:44:36 INFO]: [EssentialsSpawn] Loading EssentialsSpawn v2.13.1
[04:44:36 INFO]: [GriefPrevention] Loading GriefPrevention v8.2
[04:44:36 INFO]: [Factions] Loading Factions v2.4.0
[04:44:36 INFO]: [Autorank] Loading Autorank v3.3
[04:44:36 INFO]: [mcore] Enabling mcore v7.2.1
[04:44:37 INFO]: [mcore 7.2.1] === ENABLE START ===
[04:44:37 WARN]: Could not get latest artifact information: IOException
[04:44:37 INFO]: [mcore 7.2.1] §eLoading Playerdat datas...
[04:44:37 INFO]: [mcore 7.2.1] §eLoading Cachefile datas...
[04:44:37 INFO]: [mcore 7.2.1] §eLoading Onlineplayer datas...
[04:44:37 INFO]: [mcore 7.2.1] §eLoading Registry datas...
[04:44:37 INFO]: [mcore 7.2.1] §eLoading Dbmojangapi datas...
[04:44:37 INFO]: [mcore 7.2.1] §bPlayer Strings Found: §d0
[04:44:37 INFO]: [mcore 7.2.1] §bPlayer Strings Cached: §d0
[04:44:37 INFO]: [mcore 7.2.1] §bPlayer Strings Remaining: §d0
[04:44:37 INFO]: [mcore 7.2.1] §eNow fetching the remaining players from Mojang API ...
[04:44:37 INFO]: [mcore 7.2.1] §e ... done!
[04:44:37 INFO]: [mcore 7.2.1] §eSaving Cachefile...
[04:44:37 INFO]: [mcore 7.2.1] §eSetup of IdUtil took §d127§ems.
[04:44:37 INFO]: [mcore 7.2.1] === ENABLE §aCOMPLETE §e(Took §d706ms§e) ===
[04:44:37 INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
[04:44:39 INFO]: [Vault] Enabling Vault v1.4.1-b436
[04:44:39 INFO]: [Vault] [Economy] CraftConomy3 found: Waiting
[04:44:39 INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[04:44:39 INFO]: [Vault][Permission] PermissionsBukkit hooked.
[04:44:39 INFO]: [Vault] [Permission] PermissionsBukkit found: Waiting
[04:44:39 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[04:44:39 INFO]: [Vault] Enabled Version 1.4.1-b436
[04:44:39 INFO]: [mcore 7.2.1] §aActivated §eintegration with §dVault
[04:44:39 INFO]: Preparing level "world"
[04:44:39 INFO]: Preparing start region for level 0 (Seed: 7183121725655893182)
[04:44:40 INFO]: Preparing spawn area: 44%
[04:44:41 INFO]: Preparing spawn area: 80%
[04:44:42 INFO]: Preparing start region for level 1 (Seed: -116467174688975651)
[04:44:43 INFO]: Preparing spawn area: 59%
[04:44:44 INFO]: [WorldEdit] Enabling WorldEdit v5.6.2
[04:44:44 INFO]: WEPIF: Using the Bukkit Permissions API.
[04:44:44 INFO]: [Essentials] Enabling Essentials v2.13.1
[04:44:45 INFO]: [Vault][Economy] Essentials Economy hooked.
[04:44:45 INFO]: Essentials: Using config file enhanced permissions.
[04:44:45 INFO]: Permissions listed in as player-commands will be given to all users.
[04:44:45 INFO]: [Essentials] Payment method found (Vault - Economy: Craftconomy3 version: 1.4.1-b436)
[04:44:45 INFO]: [PermissionsBukkit] Enabling PermissionsBukkit v2.4
[04:44:45 INFO]: [PermissionsBukkit] Enabled successfully
[04:44:45 INFO]: Essentials: Using PermissionsBukkit based permissions.
[04:44:45 INFO]: [EssentialsChat] Enabling EssentialsChat v2.13.1
[04:44:45 INFO]: [Craftconomy3] Enabling Craftconomy3 v3.1.6 jenkins-Craftconomy3-2149
[04:44:45 INFO]: [Craftconomy3] Starting up!
[04:44:45 INFO]: [Craftconomy3] Loading the Configuration
[04:44:45 INFO]: [Craftconomy3] Loading listeners.
[04:44:45 INFO]: [Craftconomy3] Loading commands
[04:44:46 INFO]: [Craftconomy3] Loading the Database Manager
[04:44:47 INFO]: [Craftconomy3] Database Manager Loaded!
[04:44:47 INFO]: [Craftconomy3] Loading the Currency manager.
[04:44:47 INFO]: [Craftconomy3] Currency Manager Loaded!
[04:44:47 INFO]: [Craftconomy3] Loading default settings.
[04:44:47 INFO]: [Craftconomy3] Default settings loaded!
[04:44:47 INFO]: [Craftconomy3] Loading the Account Manager
[04:44:47 INFO]: [Craftconomy3] Account Manager Loaded!
[04:44:47 INFO]: [Craftconomy3] Loading the PayDay manager.
[04:44:47 INFO]: [Craftconomy3] PayDay Manager loaded!
[04:44:47 INFO]: [Craftconomy3] World Group Manager loaded!
[04:44:47 INFO]: [Craftconomy3] Ready!
[04:44:47 INFO]: [Vault][Economy] Craftconomy3 hooked.
[04:44:47 INFO]: [jCommands] Enabling jCommands v2.0.2
[04:44:47 INFO]: ---
[04:44:47 INFO]: [jCommands] Loaded /jCommands/config.yml
[04:44:48 INFO]: [jCommands] Initializing Commands.
[04:44:48 INFO]: [jCommands] Initializing Events.
[04:44:48 INFO]: [jCommands] jCommands v2.0.2 enabled (208 ms)
[04:44:48 INFO]: ---
[04:44:48 INFO]: [CustomJoinItems] Enabling CustomJoinItems v1.5.1
[04:44:48 INFO]: [EssentialsSpawn] Enabling EssentialsSpawn v2.13.1
[04:44:48 INFO]: [GriefPrevention] Enabling GriefPrevention v8.2
[04:44:48 INFO]: GriefPrevention: Grief Prevention boot start.
[04:44:48 INFO]: GriefPrevention: Finished loading configuration.
[04:44:48 INFO]: GriefPrevention: 3 total claims loaded.
[04:44:49 INFO]: GriefPrevention: Customizable messages loaded.
[04:44:49 INFO]: GriefPrevention: Finished loading data (File Mode).
[04:44:49 INFO]: GriefPrevention: GriefPrevention requires Vault for economy integration.
[04:44:49 INFO]: GriefPrevention: Attempting to load Vault...
[04:44:49 INFO]: GriefPrevention: Vault loaded successfully!
[04:44:49 INFO]: GriefPrevention: Looking for a Vault-compatible economy plugin...
[04:44:49 INFO]: GriefPrevention: Hooked into economy: Craftconomy3.
[04:44:49 INFO]: GriefPrevention: Ready to buy/sell claim blocks!
[04:44:49 INFO]: GriefPrevention: Boot finished.
[04:44:49 INFO]: [Factions] Enabling Factions v2.4.0
[04:44:49 INFO]: [Factions 2.4.0] === ENABLE START ===
[04:44:49 INFO]: [Factions 2.4.0] === ENABLE COMPLETE (Took 585ms) ===
[04:44:49 INFO]: [Autorank] Enabling Autorank v3.3
[04:44:49 INFO]: [Autorank] Simple config file loaded
[04:44:49 WARN]: org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in "<string>", line 17, column 13:
                rank change: Default;Novice
                ^
expected <block end>, but found Scalar
 in "<string>", line 20, column 23:
                message: 'Congratulations, you are now a N ... 
                          ^

[04:44:49 WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[04:44:49 WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226)
[04:44:49 WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169)
[04:44:49 WARN]: 	at me.armar.plugins.autorank.data.SimpleYamlConfiguration.<init>(SimpleYamlConfiguration.java:55)
[04:44:49 WARN]: 	at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:268)
[04:44:49 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[04:44:49 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[04:44:49 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[04:44:49 WARN]: 	at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:446)
[04:44:49 WARN]: 	at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:380)
[04:44:49 WARN]: 	at net.minecraft.server.v1_7_R3.MinecraftServer.n(MinecraftServer.java:352)
[04:44:49 WARN]: 	at net.minecraft.server.v1_7_R3.MinecraftServer.g(MinecraftServer.java:326)
[04:44:49 WARN]: 	at net.minecraft.server.v1_7_R3.MinecraftServer.a(MinecraftServer.java:282)
[04:44:49 WARN]: 	at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:182)
[04:44:49 WARN]: 	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:436)
[04:44:49 WARN]: 	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)
[04:44:49 WARN]: Caused by: while parsing a block mapping
 in "<string>", line 17, column 13:
                rank change: Default;Novice
                ^
expected <block end>, but found Scalar
 in "<string>", line 20, column 23:
                message: 'Congratulations, you are now a N ... 
                          ^

[04:44:49 WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:575)
[04:44:49 WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
[04:44:49 WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146)
[04:44:49 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
[04:44:49 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
[04:44:49 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
[04:44:49 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
[04:44:49 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
[04:44:49 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
[04:44:49 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
[04:44:49 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
[04:44:49 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:123)
[04:44:49 WARN]: 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:106)
[04:44:49 WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121)
[04:44:49 WARN]: 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
[04:44:49 WARN]: 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
[04:44:49 WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
[04:44:49 WARN]: 	... 15 more
[04:44:49 INFO]: [Autorank] Settings config file loaded
[04:44:49 INFO]: [Autorank] Loaded playerdata.
[04:44:49 INFO]: [Autorank] No stats plugin found! Most requirements cannot be used!
[04:44:49 INFO]: [Autorank] Loaded libraries and dependencies
[04:44:49 INFO]: [Autorank] Interval check every 60 minutes.
[04:44:49 INFO]: [Autorank] Data file loaded
[04:44:50 ERROR]: Error occurred while enabling Autorank v3.3 (Is it up to date?)
java.lang.NullPointerException
	at me.armar.plugins.autorank.config.ConfigHandler.getRanks(ConfigHandler.java:90) ~[?:?]
	at me.armar.plugins.autorank.playerchecker.builders.RankChangeBuilder.createFromAdvancedConfig(RankChangeBuilder.java:37) ~[?:?]
	at me.armar.plugins.autorank.playerchecker.PlayerChecker.initialiseFromConfigs(PlayerChecker.java:179) ~[?:?]
	at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:371) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:446) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:380) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.server.v1_7_R3.MinecraftServer.n(MinecraftServer.java:352) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.server.v1_7_R3.MinecraftServer.g(MinecraftServer.java:326) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.server.v1_7_R3.MinecraftServer.a(MinecraftServer.java:282) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:182) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:436) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
[04:44:50 INFO]: Server permissions file permissions.yml is empty, ignoring it
[04:44:50 INFO]: Done (10.632s)! For help, type "help" or "?"
[04:44:50 INFO]: [mcore 7.2.1] ============================================
[04:44:50 INFO]: [mcore 7.2.1] We are preparing for Mojangs switch to UUIDs.
[04:44:50 INFO]: [mcore 7.2.1] Learn more at: https://forums.bukkit.org/threads/psa-the-switch-to-uuids-potential-plugin-server-breakage.250915/
[04:44:50 INFO]: [mcore 7.2.1] Loading Playerdat datas...
[04:44:50 INFO]: [mcore 7.2.1] Loading Cachefile datas...
[04:44:50 INFO]: [mcore 7.2.1] Loading Onlineplayer datas...
[04:44:50 INFO]: [mcore 7.2.1] Loading Registry datas...
[04:44:50 INFO]: [mcore 7.2.1] Loading Dbmojangapi datas...
[04:44:50 INFO]: [mcore 7.2.1] Player Strings Found: 0
[04:44:50 INFO]: [mcore 7.2.1] Player Strings Cached: 0
[04:44:50 INFO]: [mcore 7.2.1] Player Strings Remaining: 0
[04:44:50 INFO]: [mcore 7.2.1] Now fetching the remaining players from Mojang API ...
[04:44:50 INFO]: [mcore 7.2.1]  ... done!
[04:44:50 INFO]: [mcore 7.2.1] Saving Cachefile...
[04:44:50 INFO]: [mcore 7.2.1] Now updating database for plugins that are ready ...
[04:44:50 INFO]: [mcore 7.2.1] Pre update factions_mplayer.
[04:44:50 INFO]: [mcore 7.2.1] Post update factions_mplayer. Took 1ms. 0/0 changed.
[04:44:50 INFO]: [mcore 7.2.1] Pre update factions_uplayer@default.
[04:44:50 INFO]: [mcore 7.2.1] Post update factions_uplayer@default. Took 1ms. 0/1 changed.
[04:44:50 INFO]: [mcore 7.2.1]  ... done!
[04:44:50 INFO]: [mcore 7.2.1] (database saving will now commence which might lock the server for a while)
[04:44:50 INFO]: [mcore 7.2.1] ============================================
>shutdown
[04:45:25 INFO]: CONSOLE: Forcing save..
[04:45:25 INFO]: CONSOLE: Save complete.
[04:45:25 INFO]: You've kicked everyone from the server!
[04:45:25 INFO]: CONSOLE: Stopping the server..
[04:45:25 INFO]: Stopping server
[04:45:25 INFO]: [Autorank] Disabling Autorank v3.3
[04:45:25 INFO]: [Autorank] Autorank 3.3 has been disabled!
[04:45:25 INFO]: [Factions] Disabling Factions v2.4.0
[04:45:25 INFO]: [Factions 2.4.0] Disabled
[04:45:25 INFO]: [GriefPrevention] Disabling GriefPrevention v8.2
[04:45:25 INFO]: GriefPrevention: GriefPrevention disabled.
[04:45:25 INFO]: [EssentialsSpawn] Disabling EssentialsSpawn v2.13.1
[04:45:25 INFO]: [Vault] Disabling Vault v1.4.1-b436
[04:45:25 INFO]: [Essentials] Payment method was disabled. No longer accepting payments.
[04:45:25 INFO]: [CustomJoinItems] Disabling CustomJoinItems v1.5.1
[04:45:25 INFO]: [mcore 7.2.1] Deactivated integration with Vault
[04:45:25 INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[04:45:26 INFO]: [jCommands] Disabling jCommands v2.0.2
[04:45:26 INFO]: [jCommands] jCommands v2.0.2 disabled (0 ms)
[04:45:26 INFO]: [Craftconomy3] Disabling Craftconomy3 v3.1.6 jenkins-Craftconomy3-2149
[04:45:26 INFO]: [Craftconomy3] Closing the connection to the database.
[04:45:26 INFO]: [EssentialsChat] Disabling EssentialsChat v2.13.1
[04:45:26 INFO]: [PermissionsBukkit] Disabling PermissionsBukkit v2.4
[04:45:26 INFO]: [Essentials] Disabling Essentials v2.13.1
[04:45:26 INFO]: Essentials: Using config file enhanced permissions.
[04:45:26 INFO]: Permissions listed in as player-commands will be given to all users.
[04:45:26 INFO]: [WorldEdit] Disabling WorldEdit v5.6.2
[04:45:26 INFO]: [mcore] Disabling mcore v7.2.1
[04:45:26 INFO]: [mcore 7.2.1] Disabled
[04:45:26 INFO]: Saving players
[04:45:26 INFO]: Saving worlds
[04:45:26 INFO]: Saving chunks for level 'world'/Overworld
[04:45:26 INFO]: Saving chunks for level 'world_nether'/Nether
[04:45:26 INFO]: Stopping server
[04:45:26 INFO]: Saving players
[04:45:26 INFO]: Saving worlds
[04:45:26 INFO]: Saving chunks for level 'world'/Overworld
>logout
[/CODE]

**Comment by Staartvin** [comment]
Closed due to inactivity.
