### ISSUE TITLE
I cant get auto rank to work

### ISSUE THREAD

**Issue by TSwolll** [Armarr/Autorank-2#149]
I have been trying to get autorank to work with the advanced config but I cant seem to find the problem. It worked fine with the simple config but as soon as i chose to do the advanced config it had problems here is my log for autorank.

[Server thread/INFO]: [Autorank] Enabling Autorank v3.3
[17:55:47] [Server thread/INFO]: [Autorank] Simple config file loaded
[17:55:47] [Server thread/INFO]: [Autorank] Advanced config file loaded
[17:55:47] [Server thread/INFO]: [Autorank] Settings config file loaded
[17:55:47] [Server thread/INFO]: [Autorank] Loaded playerdata.
[17:55:47] [Server thread/INFO]: [Autorank] Successfully established connection to 66.85.144.162:3306
[17:55:47] [Server thread/ERROR]: Error occurred while enabling Autorank v3.3 (Is it up to date?)
java.lang.NoClassDefFoundError: nl/lolmewn/stats/Main
	at me.armar.plugins.autorank.hooks.statsapi.StatsAPIHandler.get(StatsAPIHandler.java:47) ~[?:?]
	at me.armar.plugins.autorank.hooks.statsapi.StatsAPIHandler.isInstalled(StatsAPIHandler.java:264) ~[?:?]
	at me.armar.plugins.autorank.hooks.statsapi.StatsAPIHandler.setup(StatsAPIHandler.java:274) ~[?:?]
	at me.armar.plugins.autorank.hooks.DependencyManager.loadDependencies(DependencyManager.java:120) ~[?:?]
	at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:302) ~[?:?]

**Comment by Staartvin** [comment]
Closed due to inactivity.
