### ISSUE TITLE
Autorank Disabled

### ISSUE THREAD

**Issue by Havoc07** [Armarr/Autorank-2#159]
I have been having an issue with my autorank config. The settings is set to run the advanced config but the log file shows that it is only loading the simpleconfig. and It seems to be finding some issue with 

 [22:03:49] [Server thread/INFO]: [Autorank] Data file loaded
[22:03:50] [Server thread/ERROR]: Error occurred while enabling Autorank v3.3 (Is it up to date?)
java.lang.NullPointerException
    at me.armar.plugins.autorank.config.ConfigHandler.getRanks(ConfigHandler.java:90) ~[?:?]
    at me.armar.plugins.autorank.playerchecker.builders.RankChangeBuilder.createFromAdvancedConfig(RankChangeBuilder.java:37) ~[?:?]
    at me.armar.plugins.autorank.playerchecker.PlayerChecker.initialiseFromConfigs(PlayerChecker.java:179) ~[?:?]
    at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:371) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.211]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:36 [JavaPluginLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.211]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [Simpl

The Pastebin of my Autorank advanced config is here : http://pastebin.com/bdwqd2P0

**Comment by Staartvin** [comment]
Could you try the dev build 311 and see if it works now?

**Comment by TheChampTF** [comment]
I can confirm issue on latest build http://paste.yu8.me/?1dc501cf031ce733#5VblbEXxkXq1E0Uae8zPEfZTfF6PBRqh7l8F1b/LEps=

**Comment by Havoc07** [comment]
http://pastebin.com/ANMEcWUu

Above is the pastebin for what happens when I put in teh 311 build. '/plugins' tells me it is running but when I try to use teh commands as an op it tells me the plugin is disabled

**Comment by Havoc07** [comment]
You were right. Dev build #318 is working! and has even autopromoted me. Thank you and sorry for my misunderstanding. Now my final problem is with the warning I am receiving. 'Autorank Warning: Could not setup requirement 'blocks placed'! It's invalid: check the wiki for documentation'

I am using vault, it says it requires (stats) does that mean I need the Stats plugin in order for this to work?

below is the pastebin for my advanced config, please let me know if I have endered in things wrongly, I tried as best I could to understand what was given in the config and the wiki for examples.

http://pastebin.com/yHd6tYUj

**Comment by Staartvin** [comment]
Great to hear that the biggest problem is fixed. The other problem is occuring due to an incorrect format used. The blocks placed requirement follows a very specific format. You can look at the advancedconfig available at github to find the format.

**Comment by Staartvin** [comment]
Closed due to inactivity.
