### ISSUE TITLE
exceptions in console

### ISSUE THREAD

**Issue by frizzbee30** [Armarr/Autorank-2#164]
Plugin is running well, but since using the dev versions  (currently rolled back to 316, we are getting a lot of console errors. I 'm going to try an earlier version as I'm sure 314 didnt generate these.

13.01 13:25:01 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Autorank v3.4-Dev-316 generated an exception while executing task 27802

**Comment by Staartvin** [comment]
Can you provide the whole error? This is just a part of it ;)

**Comment by frizzbee30** [comment]
Hi, sorry, full error below. I haven't edited any of the config for probably 6 weeks or more, but the error has only recently appeared? 

[04:35:16] [Craft Scheduler Thread - 27/WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.4-Dev-316 generated an exception while executing task 62
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: PartialName cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.matchPlayer(CraftServer.java:458)
	at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.getWorldDataByPlayerName(WorldsHolder.java:462)
	at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.getWorldPermissionsByPlayerName(WorldsHolder.java:512)
	at net.milkbowl.vault.permission.plugins.Permission_GroupManager.playerHas(Permission_GroupManager.java:103)
	at net.milkbowl.vault.permission.Permission.has(Permission.java:61)
	at net.milkbowl.vault.permission.Permission.playerHas(Permission.java:130)
	at me.armar.plugins.autorank.leaderboard.Leaderboard.getSortedPlaytimes(Leaderboard.java:103)
	at me.armar.plugins.autorank.leaderboard.Leaderboard.updateLeaderboard(Leaderboard.java:183)
	at me.armar.plugins.autorank.leaderboard.Leaderboard$2.run(Leaderboard.java:83)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by Staartvin** [comment]
Did you recently update Vault or Groupmanager?

**Comment by frizzbee30** [comment]
yep, I updated vault to the latest version

**Comment by Staartvin** [comment]
Could you revert back to the older version of Vault temporarily to see if you still get the error. I need to know this for debugging ;) You don't have to stay at the older version.

**Comment by frizzbee30** [comment]
just run the 1.4 version of vault in test and It's generated the same error

**Comment by Staartvin** [comment]
Hmm, okay, that's good to know.

**Comment by Staartvin** [comment]
Closed due to inactivity.
