### ISSUE TITLE
Could not find name of account

### ISSUE THREAD

**Issue by ZeTaurin** [Armarr/Autorank-2#180]
I get this every time the server starts, the plugin works perfectly though but i don't like errors!

[16:55:02 INFO]: [Autorank] Could not find name of account with uuid: '70718e8c-
ab8f-3f73-a3d5-79e15d621e85'
[16:55:02 WARN]: Unexpected token END OF FILE at position 0.
[16:55:02 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.ja
va:257)
[16:55:02 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.ja
va:81)
[16:55:02 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.ja
va:75)
[16:55:02 WARN]:        at me.armar.plugins.autorank.util.uuid.NameFetcher.call(
NameFetcher.java:98)
[16:55:02 WARN]:        at me.armar.plugins.autorank.util.uuid.UUIDManager$1.run
(UUIDManager.java:176)
[16:55:02 WARN]:        at java.lang.Thread.run(Unknown Source)
[16:55:02 WARN]: Exception in thread "Craft Scheduler Thread - 10"
[16:55:02 WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.
4 generated an exception while executing task 145
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: PartialName cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.matchPlayer(CraftServer.ja
va:458)
        at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.getWorldDat
aByPlayerName(WorldsHolder.java:462)
        at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.getWorldPer
missionsByPlayerName(WorldsHolder.java:512)
        at net.milkbowl.vault.permission.plugins.Permission_GroupManager.playerH
as(Permission_GroupManager.java:103)
        at net.milkbowl.vault.permission.Permission.playerHas(Permission.java:11
3)
        at me.armar.plugins.autorank.leaderboard.Leaderboard.getSortedPlaytimes(
Leaderboard.java:106)
        at me.armar.plugins.autorank.leaderboard.Leaderboard.updateLeaderboard(L
eaderboard.java:185)
        at me.armar.plugins.autorank.leaderboard.Leaderboard$2.run(Leaderboard.j
ava:84)
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java
:71)
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more

**Comment by Staartvin** [comment]
Could you use the latest version of Autorank dev builds? (355)

**Comment by ZeTaurin** [comment]
The error is gone in the latest dev build, thank you :)
