### ISSUE TITLE
Error occurred while enabling Autorank v3.3 (Is it up to date?)

### ISSUE THREAD

**Issue by TarzanTells** [Armarr/Autorank-2#190]
Spigot w/BuildTools: version 1.8-R0.1
Autorank version: v3.3

Plugin list: (copied)
Plugins (20): GroupManager, WorldEdit, iConomy, BukkitSpeak, PluginManager, Vault, ClearLag, UltimateCore, Multiverse-Core, Questioner, LWC, WorldGuard, dynmap, HyperConomy, Jobs, WorldBorder, Autorank, StaffChat, RegionForSale, NoItem

Issue: It will not load on start up. NoClassDefFound, is this UltimateCore problem or AutoRank? (i am not a developer or coder, I don't know nothing about coding)

[14:47:57] [Server thread/INFO]: [Autorank] Enabling Autorank v3.3
[14:47:57] [Server thread/INFO]: [Autorank] Simple config file loaded
[14:47:57] [Server thread/INFO]: [Autorank] Advanced config file loaded
[14:47:57] [Server thread/INFO]: [Autorank] Settings config file loaded
[14:47:57] [Server thread/INFO]: [Autorank] Loaded playerdata.
[14:47:57] [Server thread/ERROR]: Error occurred while enabling Autorank v3.3 (Is it up to date?)
java.lang.NoClassDefFoundError: Bammerbom/UltimateCore/UltimateCore
	at me.armar.plugins.autorank.hooks.ultimatecoreapi.UltimateCoreHandler.get(UltimateCoreHandler.java:39) ~[?:?]
	at me.armar.plugins.autorank.hooks.ultimatecoreapi.UltimateCoreHandler.isInstalled(UltimateCoreHandler.java:59) ~[?:?]
	at me.armar.plugins.autorank.hooks.ultimatecoreapi.UltimateCoreHandler.setup(UltimateCoreHandler.java:69) ~[?:?]
	at me.armar.plugins.autorank.hooks.DependencyManager.loadDependencies(DependencyManager.java:120) ~[?:?]
	at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:302) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
Caused by: java.lang.ClassNotFoundException: Bammerbom.UltimateCore.UltimateCore
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_76]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_76]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_76]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_76]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_76]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_76]
	... 16 more

**Comment by TarzanTells** [comment]
I can see that I've put v3.3 of AutoRank. I have tested with v.3.4 and v3.3, both with the same error. Tested with older version to check if there stillw as an issue. I will provide the error for this as well.

[14:59:49] [Server thread/INFO]: [Autorank] Enabling Autorank v3.4
[14:59:49] [Server thread/INFO]: [Autorank] New Simple config file copied from jar
[14:59:49] [Server thread/INFO]: [Autorank] New Advanced config file copied from jar
[14:59:49] [Server thread/INFO]: [Autorank] New Settings config file copied from jar
[14:59:49] [Server thread/INFO]: [Autorank] Loaded stored uuids.
[14:59:49] [Server thread/INFO]: [Autorank] Loaded playerdata.
[14:59:49] [Server thread/ERROR]: Error occurred while enabling Autorank v3.4 (Is it up to date?)
java.lang.NoClassDefFoundError: Bammerbom/UltimateCore/UltimateCore
	at me.armar.plugins.autorank.hooks.ultimatecoreapi.UltimateCoreHandler.get(UltimateCoreHandler.java:39) ~[?:?]
	at me.armar.plugins.autorank.hooks.ultimatecoreapi.UltimateCoreHandler.isInstalled(UltimateCoreHandler.java:59) ~[?:?]
	at me.armar.plugins.autorank.hooks.ultimatecoreapi.UltimateCoreHandler.setup(UltimateCoreHandler.java:69) ~[?:?]
	at me.armar.plugins.autorank.hooks.DependencyManager.loadDependencies(DependencyManager.java:121) ~[?:?]
	at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:322) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
Caused by: java.lang.ClassNotFoundException: Bammerbom.UltimateCore.UltimateCore
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_76]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_76]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_76]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_76]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-ed3e3af-ee6d0fa]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_76]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_76]
	... 16 more

**Comment by Staartvin** [comment]
Update to the latest version of Autorank (dev version) and use UltimateCore 2.0.10

**Comment by Bammerbom** [comment]
@Staartvin Any 2.x version of UltimateCore would work

**Comment by Staartvin** [comment]
@Bammerbom Using the latest version is, most of the times, the best option ;)

**Comment by Staartvin** [comment]
Closed due to inactivity.
