### ISSUE TITLE
Plugin Autorank v3.4 generated an exception while executing task 83

### ISSUE THREAD

**Issue by Jebula999** [Armarr/Autorank-2#191]
Good Day,

I have had this specific error for a while, been trying to solve it the good ol' fashioned way, but 2 weeks later i still can't figure it out.

I have updated to the latest dev build as well as tried other versions, still no luck.

I have however tried it on a test server, and found if i use my config files from my current server, the error reproduces on the test server, yet a fresh install seems to be fine.

The problem is that because i don't know which file specifically is causing the error, i am very reluctant to replace them. 

Here is the full error:
Exception in thread "Craft Scheduler Thread - 5"
[22:35:13 WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.4 generated an exception while executing task 83
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at me.armar.plugins.autorank.util.uuid.storage.UUIDStorage.getPlayerName(UUIDStorage.java:245)
        at me.armar.plugins.autorank.util.uuid.UUIDManager.getPlayers(UUIDManager.java:130)
        at me.armar.plugins.autorank.util.uuid.UUIDManager.getPlayerFromUUID(UUIDManager.java:90)
        at me.armar.plugins.autorank.leaderboard.Leaderboard.getSortedPlaytimes(Leaderboard.java:104)
        at me.armar.plugins.autorank.leaderboard.Leaderboard.updateLeaderboard(Leaderboard.java:185)
        at me.armar.plugins.autorank.leaderboard.Leaderboard$2.run(Leaderboard.java:84)
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

If you see anything that pops out at you, please let me know, i am not good at reading error reports in the first place :P.

Thanx in advance.
-Jeb

**Comment by Jebula999** [comment]
I would like too add, after running more test that this only accurs when adding the "data.yml" file.

I took a fresh install of it on my test server, added each file one by one starting the server after each transfer, and only when i add the data.yml file it happens. I have done it in different orders and still produces the same result.

Here is the contents of my data.yml file:
c2a3018e-f441-3c7c-a073-8a25fbe36464: 4315
c035b661-80dd-35c7-8117-eb05a232544f: 95
a8d27a13-6f98-3421-a4fe-32a299d65d73: 535
d6a411df-4863-3579-ab15-5a4909d50864: 4275
a9c1dbbf-f1d2-3815-8f47-8a7b3d7e1c02: 1720
89fb8b89-13e6-39f3-95d5-7bf9ef18bbb0: 235
3334be4e-b8c9-3a36-8dc9-f4e7d8ba4e24: 45
90b190ae-a21f-334b-8d4c-177694dae2b4: 55
c30ad840-ba02-3f2e-b63d-d8830fb5b798: 600
9434c617-cdba-3f4d-82b9-d5f153a24675: 285
c24dd223-a124-39eb-8763-db67bce2e3ab: 655
f215ba52-bc18-493a-91a1-8f579f4349c9: 1715
b2156092-9e24-4993-9b8c-1a6d182b9f48: 200
693b249d-af76-3c06-bb77-1c3992ac9369: 130
adbe5a1c-1f52-3fd1-90b5-e23ab0cbb2b3: 5
2f6addcc-dd1e-3e7d-abd8-d38a9838b401: 455
7e1b580b-b4f6-37e6-a69a-456bf6903265: 5
82a608ac-617f-3eda-a8a1-ca4574283aea: 5
2ef7c53a-f081-312d-bde9-2108a63b46cc: 5
c00cb112-ee24-3fb7-af06-2e6e0621d9a1: 5
0750ea0d-e958-368c-bedc-3fffbfeafd37: 5
803b5b80-889c-3fe5-9c71-28777d1a1091: 5
db591cae-0b40-336c-87e3-be17ee131c3f: 40
dbc5375a-a94b-3448-ad7e-d4fe63a053c8: 5
35635586-b4b5-39e4-9338-a08a5ebeb4f8: 5
0b8dcf96-7166-3c76-8d9f-f63bbfed828f: 5
93014bca-0ed9-385c-99e0-fb14c8519bd6: 5
48eed77f-813b-3740-bbd6-0a77b35124d5: 5
a12890e6-df70-3b67-88de-f25b73e222bd: 290
cbebfb27-0919-35e8-9aa6-bdc3e1591850: 1055
19e0bf9c-9977-33b6-ae5d-3d55ccee4763: 1030
76729be4-100d-38e3-9015-b32a8e1dc7be: 15
761d0d31-2e0e-30bf-8152-a5cb53e95199: 215
1509d4ce-2019-3086-a523-269c48ce6e6c: 865
d0e51967-1b93-3e47-b429-71d16107a8ff: 2170
b62c3701-0e93-3b5a-8c95-99d0da6d793a: 2285
8fad20bb-48a1-4d3d-8577-e09c75836488: 5270
2bc69a6b-0349-32f7-b8ba-38273ede580c: 75
8298a9dd-870c-3e99-94ca-900f76b7609f: 5
360a3646-094e-3df7-90d3-7821e8bd003f: 5
c5ff2845-aca0-37f2-bdda-3f8e030ec5df: 5
648d28e7-a95b-355d-a6a5-39975d180bc7: 5
2e5d4490-3855-3e1a-93de-5868438a417f: 5
8dd79517-0fdc-3d1d-a666-3719c48441d6: 5
74df3063-9da6-3044-8f03-e7bc7d8dcf01: 5
83b4f119-96d5-3d12-a286-e4734f3cb6ff: 5
3c695a05-2df1-3a33-b60a-9ca4eb36bec8: 5
aa009e7b-a457-3448-8cc7-08faa3b8d425: 5
d5f49798-3cac-3697-a84f-773acc797978: 5



Regards
-Jeb

**Comment by Jebula999** [comment]
This here is the latest error.

I deleted all files relevant to player data, and all was fine till now.


[00:04:12 INFO]: [Autorank] Could not find name of account with uuid: 'd6a411df-4863-3579-ab15-5a4909d50864'
[00:04:12 WARN]: Unexpected token END OF FILE at position 0.
[00:04:12 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
[00:04:12 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
[00:04:12 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
[00:04:12 WARN]:        at me.armar.plugins.autorank.util.uuid.NameFetcher.call(NameFetcher.java:98)
[00:04:12 WARN]:        at me.armar.plugins.autorank.util.uuid.UUIDManager$1.run(UUIDManager.java:176)
[00:04:12 WARN]:        at java.lang.Thread.run(Thread.java:745)
[00:04:12 WARN]: Exception in thread "Craft Scheduler Thread - 30"
[00:04:12 WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.4 generated an exception while executing task 592
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: PartialName cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.matchPlayer(CraftServer.java:459)
        at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.getWorldDataByPlayerName(WorldsHolder.java:462)
        at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.getWorldPermissionsByPlayerName(WorldsHolder.java:512)
        at net.milkbowl.vault.permission.plugins.Permission_GroupManager.playerHas(Permission_GroupManager.java:103)
        at net.milkbowl.vault.permission.Permission.playerHas(Permission.java:113)
        at me.armar.plugins.autorank.leaderboard.Leaderboard.getSortedPlaytimes(Leaderboard.java:106)
        at me.armar.plugins.autorank.leaderboard.Leaderboard.updateLeaderboard(Leaderboard.java:185)
        at me.armar.plugins.autorank.leaderboard.Leaderboard$2.run(Leaderboard.java:84)
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53

I have traced the UUID to the specific player, but when checking all the other files it all matches up and nothing seems to be wrong with that UUID.


Any information would be great.

Regards
-Jeb

**Comment by Jebula999** [comment]
UPDATE:

I have even tried deleting EVERY file, and even when running a fresh version, with no players online, it still accurs.


It has gotten to the point where the players which UUID are showing cannot rank up further, as Autorank does not know whom they are

**Comment by Staartvin** [comment]
Have you deleted the data.yml as well?

**Comment by Jebula999** [comment]
I have, and for some reason, when they file is generated again, the file seems to still contain the same information, though i don't know where it is getting it from

**Comment by Staartvin** [comment]
Could you stop the server, delete the file, then start the server back up again?

**Comment by Jebula999** [comment]
I will do it now

**Comment by Jebula999** [comment]
This is very strange.... i feel like i have wasted your time.

I did that twice before, yet it didn't help. I do it now, and no errors occur and the data.yml file is empty.

Thank you for getting back to me on the matter, Much appreciated, if anything happens i will let you know.

-Jeb

**Comment by Staartvin** [comment]
Good to hear ;) I'll close it for now. Open a new ticket if you get any errors.
