### ISSUE TITLE
Error on "MySQLWrapper"

### ISSUE THREAD

**Issue by FabioZumbi12** [Armarr/Autorank-2#223]
Heres the exception:

[03:19:41 WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.5.1 generated an exception while executing task 94
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at me.armar.plugins.autorank.mysql.wrapper.MySQLWrapper.setGlobalTime(MySQLWrapper.java:177)
        at me.armar.plugins.autorank.playtimes.Playtimes.setGlobalTime(Playtimes.java:389)
        at me.armar.plugins.autorank.playtimes.Playtimes.modifyGlobalTime(Playtimes.java:360)
        at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:55)
        at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:76)
        at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.run(PlaytimesUpdate.java:30)
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

The server version and ar version is in the log, thanks :)

**Comment by FabioZumbi12** [comment]
No solution? Still happening :(

**Comment by Staartvin** [comment]
Could you update to the latest dev build and try again?

**Comment by FabioZumbi12** [comment]
Is the Autorank-3.5.1-Dev-383.jar version? I will try! Thanks.

**Comment by Staartvin** [comment]
Yup!

**Comment by FabioZumbi12** [comment]
The same error still:

[15:48:48 WARN]: Exception in thread "Craft Scheduler Thread - 1749"
[15:48:48 WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.5.1 generated an exception while executing task 78
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at me.armar.plugins.autorank.mysql.wrapper.MySQLWrapper.setGlobalTime(MySQLWrapper.java:177)
        at me.armar.plugins.autorank.playtimes.Playtimes.setGlobalTime(Playtimes.java:389)
        at me.armar.plugins.autorank.playtimes.Playtimes.modifyGlobalTime(Playtimes.java:360)
        at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:55)
        at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:76)
        at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.run(PlaytimesUpdate.java:30)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by Staartvin** [comment]
Could you show me your whole startup log?

**Comment by Staartvin** [comment]
Closed due to inactivity.
