### ISSUE TITLE
NullPointerException?

### ISSUE THREAD

**Issue by LFCoding** [Armarr/Autorank-2#226]
Hey guys!
Just dropping by to ask if you by any chance could help me with this error?
I've tested with the latest dev build (3.5.1 atm).
Thank you in advance.

Log:
```[00:30:14] [Server thread/ERROR]: Error occurred while enabling Autorank v3.5.1-Dev-381 (Is it up to date?)
java.lang.NullPointerException
	at me.armar.plugins.autorank.config.ConfigHandler.getRanks(ConfigHandler.java:87) ~[?:?]
	at me.armar.plugins.autorank.playerchecker.builders.RankChangeBuilder.createFromAdvancedConfig(RankChangeBuilder.java:37) ~[?:?]
	at me.armar.plugins.autorank.playerchecker.PlayerChecker.initialiseFromConfigs(PlayerChecker.java:179) ~[?:?]
	at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:394) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.reload(CraftServer.java:746) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.Bukkit.reload(Bukkit.java:534) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-870264a-0a645a2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-870264a-0a645a2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]```



And my rank config:
```#############################################################################
#                                                                           #
#                   Autorank 2 Advanced Config                              #
#                                                                           #
#   Please use the SimpleConfig unless you know what you are doing and      #
#   need functionality that the SimpleConfig doesn't provide.               #
#                                                                           #
#############################################################################

ranks:
Lvl 1 Hobbit:
        requirements:
            time:
                value: 0h
        results:
            rank change: Lvl 1 Hobbit;Lvl 2 Hobbit
            command: 'say &p blev en ny rank!; broadcast &p blev precis Lvl 1 Hobbit!;'
            message: 'Grattis, du har blivit Lvl 1 Hobbit.'
Lvl 2 Hobbit:
        requirements:
            time:
                value: 2h
            money:
                value: 1000
        results:
            rank change: Lvl 2 Hobbit;Lvl 3 Hobbit
            command: 'say &p blev en ny rank!; broadcast &p blev precis Lvl 2 Hobbit!; adjustbonusclaimblocks &p 400'
            message: 'Grattis, du har blivit Lvl 2 Hobbit. Du har nu 400 fler claimblocks!'
Lvl 3 Hobbit:
        requirements:
            time:
                value: 5h
            money:
                value: 2000
            items crafted:
                value: 50
        results:
            rank change: Lvl 2 Hobbit;Lvl 3 Hobbit
            command: 'say &p blev en ny rank!; broadcast &p blev precis Lvl 3 Hobbit!; adjustbonusclaimblocks &p 550'
            message: 'Grattis, du har blivit Lvl 3 Hobbit. Du har nu 550 fler claimblocks!'
Lvl 4 Dvärg:
        requirements:
            time:
                value: 9h
            money:
                value: 4000
        results:
            rank change: Lvl 3 Hobbit;Lvl 4 Dvärg
            command: 'say &p blev en ny rank!; broadcast &p blev precis Lvl 4 Dvärg!; adjustbonusclaimblocks &p 750'
            message: 'Grattis, du har blivit Lvl 4 Dvärg. Du har nu 750 fler claimblocks!'
Lvl 5 Dvärg:
        requirements:
            time:
                value: 14h
            money:
                value: 8000
        results:
            rank change: Lvl 4 Dvärg;Lvl 5 Dvärg
            command: 'say &p blev en ny rank!; broadcast &p blev precis Lvl 5 Dvärg!; adjustbonusclaimblocks &p 1000'
            message: 'Grattis, du har blivit Lvl 5 Dvärg. Du har nu 1000 fler claimblocks!'
Lvl 6 Dvärg:
        requirements:
            time:
                value: 20h
            money:
                value: 14000
            items crafted:
                value: 100;
        results:
            rank change: Lvl 5 Dvärg;Lvl 6 Dvärg
            command: 'say &p blev en ny rank!; broadcast &p blev precis Lvl 6 Dvärg!; adjustbonusclaimblocks &p 1300'
            message: 'Grattis, du har blivit Lvl 6 Dvärg. Du har nu 1300 fler claimblocks!'
Lvl 7 Ent:
        requirements:
            time:
                value: 27h
            money:
                value: 21000
        results:
            rank change: Lvl 6 Dvärg;Lvl 7 Ent
            command: 'say &p blev en ny rank!; broadcast &p blev precis Lvl 7 Ent!; adjustbonusclaimblocks &p 1650'
            message: 'Grattis, du har blivit Lvl 7 Ent. Du har nu 1650 fler claimblocks!'
Lvl 8 Ent:
        requirements:
            time:
                value: 35h
            money:
                value: 29000
        results:
            rank change: Lvl 7 Dvärg;Lvl 8 Ent
            command: 'say &p blev en ny rank!; broadcast &p blev precis Lvl 8 Ent!; adjustbonusclaimblocks &p 2050'
            message: 'Grattis, du har blivit Lvl 8 Ent. Du har nu 2050 fler claimblocks!'
Lvl 9 Ent:
        requirements:
            time:
                value: 44h
            money:
                value: 38000
            mobs killed: 
                value: 100
        results:
            rank change: Lvl 8 Dvärg;Lvl 9 Ent
            command: 'say &p blev en ny rank!; broadcast &p blev precis Lvl 9 Ent!; adjustbonusclaimblocks &p 2500'
            message: 'Grattis, du har blivit Lvl 9 Ent. Du har nu 2500 fler claimblocks!'
Lvl 10 Krigare:
        requirements:
            time:
                value: 54h
            money:
                value: 48000
        results:
            rank change: Lvl 9 Dvärg;Lvl 10 Krigare
            command: 'say &p blev en ny rank!; broadcast &p blev precis Lvl 10 Krigare!; adjustbonusclaimblocks &p 3000'
            message: 'Grattis, du har blivit Lvl 10 Krigare. Du har nu 3000 fler claimblocks!'
Lvl 11 Krigare:
        requirements:
            time:
                value: 65h
            money:
                value: 59000
        results:
            rank change: Lvl 10 Krigare; Lvl 11 Krigare
            command: 'say &p blev en ny rank!; broadcast &p blev precis Lvl 11 Krigare!; adjustbonusclaimblocks &p 4150'
            message: 'Grattis, du har blivit Lvl 11 Krigare. Du har nu 4150 fler claimblocks!'
Lvl 12 Krigare:
        requirements:
            time:
                value: 77h
            money:
                value: 71000
            mobs killed: 
                value: 150
        results:
            rank change: Lvl 11 Krigare; Lvl 12 Krigare
            command: 'say &p blev en ny rank!; broadcast &p blev precis Lvl 12 Krigare!; adjustbonusclaimblocks &p 4750'
            message: 'Grattis, du har blivit Lvl 12 Krigare. Du har nu 4750 fler claimblocks!'
Lvl 13 Riddare:
        requirements:
            time:
                value: 90h
            money:
                value: 84000
        results:
            rank change: Lvl 12 Krigare; Lvl 13 Riddare
            command: 'say &p blev en ny rank!; broadcast &p blev precis Lvl 13 Riddare!; adjustbonusclaimblocks &p 5400'
            message: 'Grattis, du har blivit Lvl 13 Riddare. Du har nu 5400 fler claimblocks!'
Lvl 14 Riddare:
        requirements:
            time:
                value: 104h
            money:
                value: 98000
        results:
            rank change: Lvl 13 Riddare; Lvl 14 Riddare
            command: 'say &p blev en ny rank!; broadcast &p blev precis Lvl 14 Riddare!; adjustbonusclaimblocks &p 6100'
            message: 'Grattis, du har blivit Lvl 14 Riddare. Du har nu 6100 fler claimblocks!'
Lvl 15 Riddare:
        requirements:
            time:
                value: 104h
            money:
                value: 113000
            mobs killed: 
                value: 119h
        results:
            rank change: Lvl 14 Riddare; Lvl 15 Riddare
            command: 'say &p blev en ny rank!; broadcast &p blev precis Lvl 15 Riddare!; adjustbonusclaimblocks &p 6850'
            message: 'Grattis, du har blivit Lvl 15 Riddare. Du har nu 6850 fler claimblocks!'
Lvl 16 Trollkarl:
        requirements:
            time:
                value: 135h
            money:
                value: 129000
        results:
            rank change: Lvl 15 Riddare; Lvl 16 Trollkarl
            command: 'say &p blev en ny rank!; broadcast &p blev precis Lvl 16 Trollkar!; adjustbonusclaimblocks &p 7650'
            message: 'Grattis, du har blivit Lvl 16 Trollkar. Du har nu 7650 fler claimblocks!'
Lvl 17 Trollkarl:
        requirements:
            time:
                value: 152h
            money:
                value: 146000
        results:
            rank change: Lvl 16 Riddare; Lvl 17 Trollkarl
            command: 'say &p blev en ny rank!; broadcast &p blev precis Lvl 17 Trollkar!; adjustbonusclaimblocks &p 8500'
            message: 'Grattis, du har blivit Lvl 17 Trollkar. Du har nu 8500 fler claimblocks!'
Lvl 18 Trollkarl:
        requirements:
            time:
                value: 170h
            money:
                value: 164000
        results:
            rank change: Lvl 17 Riddare; Lvl 18 Trollkarl
            command: 'say &p blev en ny rank!; broadcast &p blev precis Lvl 18 Trollkar!; adjustbonusclaimblocks &p 9400'
            message: 'Grattis, du har blivit Lvl 18 Trollkar. Du har nu 9400 fler claimblocks!'
# new requirements and results can be added by other plugins that hook into the Autorank API
# these are the ones that are included in the main plugin:
# 
#   requirements:
#       time: 1d 1h 1m
#       exp: 20 (level)
#       money: 2000 (requires vault ! Player has to have at least this amount of money)
#       world: world_nether (player has to be in this world to get ranked)
#       gamemode: 1 (player has to have a certain gamemode, 0 = Survival mode, 1 = Creative mode, 2 = Adventure mode)
#       has item: id(;amount;data;name;false/true) (checks the players inventory for the item, the name would be the display name of the item. When the false/true (boolean) parameter is true, the player should have the item with the given display name, if it is false, the player only needs the specific amount and material type.)
#       blocks broken: id(;amount;data;name) (a player has to have broken x amount blocks of item id and data) (Requires Stats) (when no data or amount is given, it will check total blocks)
#       Example: break 10 magenta wool would be: 'blocks broken: 35;10;2' 35 = itemid, 10 = amount, 2 = damagevalue
#       blocks placed: id(;amount;data) (a player has to have placed x amount blocks of item id and data) (Requires Stats) (when no data or amount is given, it will check total blocks)
#       votes: 10 (player has to have voted at least 10 times) (Requires Stats and Votifier)
#       damage taken: 10 (player has to have taken 10 damage) (damage is not counted in hearts) (Requires Stats)
#       mobs killed: 5;spider (player has to have killed 5 spiders) (if no entity is specified, then any kill counts) (Requires Stats) (for a list of entities: http://jd.bukkit.org/rb/apidocs/org/bukkit/entity/EntityType.html)
#       location: x;y;z;world;radius (player has to be in a location or within its radius)
#       faction power: 10 (Amount of power a faction has to have) (Requires Factions)
#       players killed: 10 (Player has to kill at least 10 players) (Requires Stats)
#       global time: 10d 1h 5m (Player has to be online for at least 10 days, 1 hour and 5 mins) (Global time is the accumulated time over all servers you have connected the MySQL database with)
#       total time: 50d 1h (Player has to be with this server for at least 50 days and 1 hour) (The time from when the player joined for the first time is the reference point. This means that when a player has joined 3 weeks ago, his 'total time' = 3 weeks)
#       blocks moved: 1000;0 (Player has to move at least an x amount of blocks. Second argument is what kind of movement: 0=walk, 1=boat, 2=train, 3=pig, 4=pig in train, 5=horse) (Need Stats for this)
#       worldguard region: TestRegion (Player has to be in a certain WorldGuard region) (requires WorldGuard)
#       mcmmo skill level: 100;mining (Player has to have at least level 100 in mining) (requires McMMO)
#       mcmmo power level: 100 (Player has to have at least power level 100) (requires McMMO)
#       permission: i.need.a.permission (Player has to have this permission)
#       fish caught: 10 (Player has to have caught at least 10 fish) (requires Stats)
#       items crafted: 7 (Player has to have crafted at least 7 items) (requires Stats)
#       times sheared: 15 (Player has to have sheared at least 15 sheep) (requires Stats)
#       essentials geoip location: Netherlands (Player has to be in the area 'Netherlands') (requires Essentials GeoIP)
#       in biome: river (Player has to be in biome 'river') (a list of all biomes: https://hub.spigotmc.org/javadocs/spigot/)
#
#   results:
#       rank change: new-rank
#       rank change: old-rank; new-rank
#       rank change: old-rank; new-rank; world (only works for permissions plugins that support this)
#       message: 'You got ranked up'
#       command: 'say &p hi; give &p 1 100'(executes a console command. &p will be replaced by the player name) You can perform more commands with the ';' sign.
#       effect: STEP_SOUND;8 (first argument is the effect name, second is the effect data. For a list of possible effects go to http://jd.bukkit.org/rb/doxygen/d8/db9/enumorg_1_1bukkit_1_1Effect.html)
#       tp: x;y;z;world;yaw;pitch (tp: 0;0;0;world_nether;1.0;2.0)
#       firework: target;power;type;R;G;B (Spawn a firework with on a player or spawn, with specified power, type and RGB colour) (target can be 'player' or 'spawn', power is an integer, type is a type (see http://jd.bukkit.org/rb/doxygen/d0/d54/enumorg_1_1bukkit_1_1FireworkEffect_1_1Type.html), R;G;B is a RGB colour code (see http://www.rapidtables.com/web/color/RGB_Color.htm))```

**Comment by Staartvin** [comment]
Your config is not properly formatted. It should look like this: http://pastebin.com/siQmsr8p

**Comment by Staartvin** [comment]
Closed due to inactivity.
