### ISSUE TITLE
Error Ocurred enabling autoranks

### ISSUE THREAD

**Issue by Buxieda** [Armarr/Autorank-2#241]
I cant get auto ranks to start it was working for a while but then quit.
the errors mention perworld plugin but it was working before even with pweworldplugin installed.

i have tried everything upated protocollib, PWP even the latest Spigot server build.
and the error is the same. I deleted the config files and let hem recreate and edited them to match my ranks and i still get the error:

[13:15:16] [Server thread/ERROR]: Error occurred while enabling Autorank v3.5.1-Dev-396 (Is it up to date?)
java.lang.NoClassDefFoundError: nl/lolmewn/stats/api/stat/Stat
	at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:323) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-f27339c]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.7.jar:git-Spigot-f928e7a-f27339c]
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:141) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.7.jar:git-Spigot-f928e7a-f27339c]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.7.jar:git-Spigot-f928e7a-f27339c]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.7.jar:git-Spigot-f928e7a-f27339c]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418) [spigot-1.8.7.jar:git-Spigot-f928e7a-f27339c]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382) [spigot-1.8.7.jar:git-Spigot-f928e7a-f27339c]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.8.7.jar:git-Spigot-f928e7a-f27339c]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256) [spigot-1.8.7.jar:git-Spigot-f928e7a-f27339c]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot-1.8.7.jar:git-Spigot-f928e7a-f27339c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: nl.lolmewn.stats.api.stat.Stat
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-f27339c]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-f27339c]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	... 13 

Please advise.
Thank you.

**Comment by Staartvin** [comment]
You're using a dev version of Autorank. This version of Autorank requires Stats 3. You are probably running Stats 2. You can either downgrade to Autorank 3.5.1 and use Stats 2 or upgrade Stats to version 3 and run Autorank 3.5.1 dev version.

**Comment by Buxieda** [comment]
I don't use stats. like i found out by you that there is a plugin name stats.
id it required in order for autorank to work? because it was working before something happened and its started doing this.  i deleted the config files and let it recreate them thinking that the config files might be corrupted.  nope. same issue.

**Comment by Buxieda** [comment]
here are my plugins:
[13:47:33 INFO]: Plugins (76): CleanroomGenerator, HiveJumpPads, PluginTools, FirstLastSeen, JustAFK, BarAPI,
PerWorldPlugins, HeadHunting, Quake, TeleportSigns, BatGun, AntiCriticalCheat, LobbyBow, Actionbar, AsyncWorld
EditInjector, CoreProtect, Deadbolt, WorldEdit, Essentials, CompatNoCheatPlus, RandomLocationTeleporter, Crack
Shot, WelcomeTitle, ActionHealth, Votifier, OpMe, ProtocolLib, LibsDisguises, NoCheatPlus, WhoBannedMe, Twitch
Notice, TNTTag, EssentialsChat, BlocksHub, PermissionsEx, TreeAssist, GAListener, Vault, Guilt, BlocksHub-Core
Protect, EnjinMinecraftPlugin, DisguiseCraft, Jail, PlotSquared, WorldGuard, BungeePortals, BlocksHub-WorldGua
rd, ChestCommands, EssentialsProtect, EssentialsGeoIP, EssentialsAntiBuild, EssentialsSpawn, TitleManager, Cra
ckShotShop, MCBans, Autorank, TNTRun, Multiverse-Core, FreeBungeeChat, AsyncWorldEdit, EchoPet, BungeeTabListP
lus_BukkitBridge, MineResetLite, GriefPrevention, MobArena, BlocksHub-GriefPrevention-8x, HolographicDisplays,
 Multiverse-Inventories, AsyncWorldEdit-TitleManager, LimitedCreative, iZone, BlockHunt, uSkyBlock, Paintball,
 WarpPortals, AsyncWorldEdit-WelcomeTitle
