### ISSUE TITLE
Autorank v3.5.1 not hooking with Stats v3.0.1-DEV

### ISSUE THREAD

**Issue by piecrustyumyum** [Armarr/Autorank-2#247]
[14:12:11] [Server thread/INFO]: [Autorank] Enabling Autorank v3.5.1
[14:12:11] [Server thread/INFO]: [Autorank] Simple config file loaded
[14:12:11] [Server thread/INFO]: [Autorank] Advanced config file loaded
[14:12:11] [Server thread/INFO]: [Autorank] Settings config file loaded
[14:12:12] [Server thread/INFO]: [Autorank] Loaded stored uuids.
[14:12:12] [Server thread/INFO]: [Autorank] Loaded playerdata.
[14:12:12] [Server thread/ERROR]: Error occurred while enabling Autorank v3.5.1 (Is it up to date?)
java.lang.IncompatibleClassChangeError: Found interface nl.lolmewn.stats.Main, but class was expected
    at me.armar.plugins.autorank.hooks.statsapi.StatsAPIHandler.setup(StatsAPIHandler.java:301) ~[?:?]
    at me.armar.plugins.autorank.hooks.DependencyManager.loadDependencies(DependencyManager.java:134) ~[?:?]
    at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:323) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[minecraft_server.jar:git-Spigot-d2856ae-8f0f4ed]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [minecraft_server.jar:git-Spigot-d2856ae-8f0f4ed]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [minecraft_server.jar:git-Spigot-d2856ae-8f0f4ed]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [minecraft_server.jar:git-Spigot-d2856ae-8f0f4ed]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [minecraft_server.jar:git-Spigot-d2856ae-8f0f4ed]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418) [minecraft_server.jar:git-Spigot-d2856ae-8f0f4ed]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382) [minecraft_server.jar:git-Spigot-d2856ae-8f0f4ed]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337) [minecraft_server.jar:git-Spigot-d2856ae-8f0f4ed]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256) [minecraft_server.jar:git-Spigot-d2856ae-8f0f4ed]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [minecraft_server.jar:git-Spigot-d2856ae-8f0f4ed]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_79]

**Comment by Staartvin** [comment]
You are using Stats 3, but Autorank 3.5.1 only supports Stats 2.
