### ISSUE TITLE
Autorank plugin not loading configs and not activating

### ISSUE THREAD

**Issue by MAGxZOMBIES** [Armarr/Autorank-2#252]
I am using the CB 1.7.9-R0.2 Dec 12, 2014 version of Autorank and I am running this with a 1.7.10 bukkit server and constantly when i attempt to load up Autorank the plugin automatically loads up the simple config even after i have changed it to the advanced config in the settings.yml document and then in the logs the same error keeps getting thrown up while enabling it:
[16:15:11] [Server thread/INFO]: [Autorank] Enabling Autorank v3.4
[16:15:11] [Server thread/INFO]: [Autorank] Simple config file loaded
[16:15:11] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
found character 	'\t' that cannot start any token
 in "<string>", line 29, column 1:
    			
    ^

[16:15:11] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[16:15:11] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226)
[16:15:11] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169)
[16:15:11] [Server thread/WARN]: 	at me.armar.plugins.autorank.data.SimpleYamlConfiguration.<init>(SimpleYamlConfiguration.java:55)
[16:15:11] [Server thread/WARN]: 	at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:279)
[16:15:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[16:15:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[16:15:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[16:15:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:464)
[16:15:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:398)
[16:15:11] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:386)
[16:15:11] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:360)
[16:15:11] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:316)
[16:15:11] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:192)
[16:15:11] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:472)
[16:15:11] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[16:15:11] [Server thread/WARN]: Caused by: while scanning for the next token
found character 	'\t' that cannot start any token
 in "<string>", line 29, column 1:
    			
    ^

[16:15:11] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358)
[16:15:11] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:179)
[16:15:11] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:563)
[16:15:11] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
[16:15:11] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146)
[16:15:11] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
[16:15:11] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
[16:15:11] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
[16:15:11] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
[16:15:11] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
[16:15:11] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
[16:15:11] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
[16:15:11] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
[16:15:11] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:123)
[16:15:11] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:106)
[16:15:11] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121)
[16:15:11] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
[16:15:11] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
[16:15:11] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
[16:15:11] [Server thread/WARN]: 	... 15 more
[16:15:11] [Server thread/INFO]: [Autorank] Settings config file loaded

Then once the server is fully loaded the plugin seems to be disabled as when i do /autorank the console responds saying the plugin is disabled check the system.log.

**Comment by Staartvin** [comment]
Can you show me your AdvancedConfig? There is an error in your config.

**Comment by MAGxZOMBIES** [comment]
im sorry do u have a file hosting site i could use or should i just paste it

**Comment by Staartvin** [comment]
You can use pastebin!

**Comment by MAGxZOMBIES** [comment]
http://pastebin.com/TVGzS9xk

just saying this is a incomplete version as this was to test what i had so far

**Comment by MAGxZOMBIES** [comment]
is there any issues with it?

**Comment by MAGxZOMBIES** [comment]
nevermind i think i have fixed the issue
