### ISSUE TITLE
Issue with MCMMO Power Level and Fish Caught

### ISSUE THREAD

**Issue by xwerswoodx** [Armarr/Autorank-2#287]
When I use mcmmo credit requirement on config it gives error when I join server;

```
[16:37:05] [Server thread/INFO]: [Autorank] Autorank 3.7.2 has been enabled!
[16:37:05] [Server thread/INFO]: [Autorank debug] Autorank debug is turned on!
[16:37:06] [Craft Scheduler Thread - 13/INFO]: [Autorank debug] Saving all data files...
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]  ------------------- ChangeGroup debug info ------------------- 
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] Group: neophyte
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] - neophyte
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 6 requirements
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 3 results
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] ----------------------------
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] Group: expert
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] - expert
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 6 requirements
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 3 results
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] ----------------------------
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] Group: adept
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] - adept
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 5 requirements
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 3 results
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] ----------------------------
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] Group: starter
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] - starter
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 3 requirements
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 3 results
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] ----------------------------
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] Group: newbie
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] - newbie
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 6 requirements
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 3 results
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] ----------------------------
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] Group: competent
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] - competent
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 7 requirements
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 3 results
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] ----------------------------
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] Group: amateur
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] - amateur
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 6 requirements
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 3 results
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] ----------------------------
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] Group: scholar
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] - scholar
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 6 requirements
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 3 results
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] ----------------------------
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] Group: skilled
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] - skilled
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 7 requirements
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 3 results
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] ----------------------------
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] Group: professional
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] - professional
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 7 requirements
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 3 results
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] ----------------------------
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] Group: veteran
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] - veteran
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 7 requirements
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 3 results
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] ----------------------------
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] Group: talented
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] - talented
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 6 requirements
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 3 results
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] ----------------------------
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] Group: stranger
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] - stranger
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 4 requirements
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 3 results
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] ----------------------------
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] Group: journeyman
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] - journeyman
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 7 requirements
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 3 results
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] ----------------------------
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] Group: apprentice
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] - apprentice
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 6 requirements
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 3 results
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] ----------------------------
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] Group: novice
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] - novice
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 7 requirements
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug]     - 3 results
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank debug] ----------------------------
[16:37:10] [Craft Scheduler Thread - 14/INFO]: [Autorank] Config files have been correctly setup!
[16:38:06] [Craft Scheduler Thread - 1/INFO]: [Autorank debug] Saving all data files...
[16:39:06] [Craft Scheduler Thread - 13/INFO]: [Autorank debug] Saving all data files...
[16:39:17] [Server thread/INFO]: xwerswoodx lost connection: Disconnected
[16:39:17] [Server thread/INFO]: xwerswoodx left the game.
[16:39:20] [User Authenticator #3/INFO]: UUID of player xwerswoodx is 71642e8e-98df-4590-8b24-456160e67887
[16:39:20] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Autorank v3.7.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.NoSuchMethodError: com.gmail.nossr50.api.ExperienceAPI.getPowerLevelOffline(Ljava/util/UUID;)I
	at me.armar.plugins.autorank.hooks.mcmmoapi.McMMOHandler.getPowerLevel(McMMOHandler.java:63) ~[?:?]
	at me.armar.plugins.autorank.playerchecker.requirement.McMMOPowerLevelRequirement.meetsRequirement(McMMOPowerLevelRequirement.java:40) ~[?:?]
	at me.armar.plugins.autorank.rankbuilder.ChangeGroup.checkRequirements(ChangeGroup.java:147) ~[?:?]
	at me.armar.plugins.autorank.rankbuilder.ChangeGroup.applyChange(ChangeGroup.java:80) ~[?:?]
	at me.armar.plugins.autorank.playerchecker.PlayerChecker.checkPlayer(PlayerChecker.java:81) ~[?:?]
	at me.armar.plugins.autorank.listeners.PlayerJoinListener.onPlayerJoin(PlayerJoinListener.java:53) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	... 14 more
[16:39:20] [Server thread/INFO]: xwerswoodx[/127.0.0.1:64023] logged in with entity id 376 at ([world]-143.0085399332508, 68.0, 269.3787783213996)
```

Also fish caught requirements never increases, I catch fish but still have 0 fish caught. I am using stats 3.0.2 and autorank 3.7.2.

**Comment by Staartvin** [comment]
Which of mcmmo are you using? You need the latest version of McMMO from SpigotMC!

**Comment by Staartvin** [comment]
Closed due to inactivity.
