### ISSUE TITLE
Autorank disenable please look serverlog

### ISSUE THREAD

**Issue by Neotras** [Armarr/Autorank-2#356]
hi here my log what wrong?
`[21:44:28] [Server thread/INFO]: [Autorank] Enabling Autorank v3.8
[21:44:28] [Server thread/INFO]: [Autorank] Simple config file loaded
[21:44:28] [Server thread/INFO]: [Autorank] Advanced config file loaded
[21:44:28] [Server thread/INFO]: [Autorank] Settings config file loaded
[21:44:28] [Server thread/INFO]: [Autorank] Internal properties file loaded
[21:44:28] [Server thread/INFO]: [Autorank] Backup data file loaded (backup-data.yml)
[21:44:28] [Server thread/INFO]: [Autorank] Loaded playerdata.
[21:44:28] [Server thread/INFO]: [Autorank] No stats plugin found! Most requirements cannot be used!
[21:44:28] [Server thread/INFO]: [Autorank] Loaded libraries and dependencies
[21:44:28] [Server thread/INFO]: [Autorank] Interval check every 5 minutes.
[21:44:28] [Server thread/INFO]: [Autorank] Total data file loaded
[21:44:28] [Server thread/INFO]: [Autorank] Daily data file loaded
[21:44:28] [Server thread/INFO]: [Autorank] Weekly data file loaded
[21:44:28] [Server thread/INFO]: [Autorank] Monthly data file loaded
[21:44:28] [Server thread/ERROR]: Error occurred while enabling Autorank v3.8 (Is it up to date?)
java.lang.NoClassDefFoundError: me/staartvin/statz/hooks/Dependency
	at me.armar.plugins.autorank.permissions.handlers.VaultPermissionsHandler.<init>(VaultPermissionsHandler.java:25) ~[?:?]
	at me.armar.plugins.autorank.permissions.PermissionsPluginManager.searchPermPlugin(PermissionsPluginManager.java:81) ~[?:?]
	at me.armar.plugins.autorank.permissions.PermissionsPluginManager.<init>(PermissionsPluginManager.java:38) ~[?:?]
	at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:295) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416) [spigot.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381) [spigot.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336) [spigot.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [spigot.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot.jar:git-Spigot-6016ac7-10c10b3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.ClassNotFoundException: me.staartvin.statz.hooks.Dependency
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_74]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74]
	... 15 more`

**Comment by Staartvin** [comment]
You'll need [Statz ](https://www.spigotmc.org/threads/statz.161904/) to run Autorank!
