### ISSUE TITLE
Autorank is disabled. Check your server.log! and failure. (Autorank is disabled. Check your server.log! y fallo)

### ISSUE THREAD

**Issue by TKStranger** [Armarr/Autorank-2#361]
No se que hacer me dice este error:
I do not tell me this failure:

[19:29:19 ERROR]: Error occurred while enabling Autorank v3.5 (Is it up to date?)
java.lang.NoClassDefFoundError: com/gmail/nossr50/api/exceptions/McMMOPlayerNotFoundException
        at me.armar.plugins.autorank.hooks.DependencyManager.<init>(DependencyManager.java:62) ~[?:?]
        at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:320) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Spigot.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Spigot.jar:git-Spigot-6d16e64-b105298]
        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:141) [PerWorldPlugins.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Spigot.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [Spigot.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [Spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [Spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [Spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [Spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [Spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [Spigot.jar:git-Spigot-6d16e64-b105298]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.api.exceptions.McMMOPlayerNotFoundException
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot.jar:git-Spigot-6d16e64-b105298]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        ... 14 more

Y después cuando pongo esto: "/autoranck" me salta esto:
"Autorank is disabled. Check your server.log!"
Por lo que se hay que activarlo pero no se donde esta el archivo .log y no sabría como activarlo.
Y otra cosa me descargue la ultima version 3.8 y me daba el mismo error 
Si me pueden decir eso se los agraceria.

And then when I put this: "/ autoranck" I jump this:
"Autorank is disabled. Check your server.log!"
As must be activated but not to this the .log file and not know how to activate it.
And another thing I download the latest version 3.8 and gave me the same fail

**Comment by TKStranger** [comment]
Ya lo corregi, para los que tienen errores con este plugin y no saben que hacer los ayudo!
Lo unico que tienen que hacer es tener el autorank obviamente y el Statz que se encuebtra en el siguiente link: https://www.spigotmc.org/threads/statz.161904/

**Comment by Staartvin** [comment]
I'm awfully sorry. I cannot speak not read Spanish and from I get none the wiser from Google Translate

**Comment by TKStranger** [comment]
Bue aprendan hablar español

**Comment by Staartvin** [comment]
Sorry, but it is ridiculous for me to learn Spanish at this point. I'm closing this issue. Please report back in English.
