### ISSUE TITLE
Errors using Java 8, Spigot 1.8.9.

### ISSUE THREAD

**Issue by TheIntelloBox** [Armarr/Autorank-2#384]
[10:54:39] [Craft Scheduler Thread - 1673/WARN]: Exception in thread "Craft Scheduler Thread - 1673" 
[10:54:39] [Craft Scheduler Thread - 1673/WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.8.4 generated an exception while executing task 288
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:39)
    at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.updateMinutesPlayed(PlaytimesUpdate.java:85)
    at me.armar.plugins.autorank.playtimes.PlaytimesUpdate.run(PlaytimesUpdate.java:30)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

**Comment by Staartvin** [comment]
How often do you get this specific error message?

**Comment by TheIntelloBox** [comment]
Mhh, sometimes, I think.
