### ISSUE TITLE
CommandException: Unhandled exception executing command 'autorank' in plugin Autorank v3.8.4

### ISSUE THREAD

**Issue by AgentCortez** [Armarr/Autorank-2#386]
`[09:35:39] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'autorank' in plugin Autorank v3.8.4
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
    at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
    at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
    at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
    at me.armar.plugins.autorank.statsmanager.handlers.StatsHandler.getNormalStat(StatsHandler.java:45) ~[?:?]
    at me.armar.plugins.autorank.playerchecker.requirement.MobKillsRequirement.meetsRequirement(MobKillsRequirement.java:56) ~[?:?]
    at me.armar.plugins.autorank.rankbuilder.holders.RequirementsHolder.meetsRequirement(RequirementsHolder.java:79) ~[?:?]
    at me.armar.plugins.autorank.commands.CheckCommand.check(CheckCommand.java:143) ~[?:?]
    at me.armar.plugins.autorank.commands.CheckCommand.onCommand(CheckCommand.java:296) ~[?:?]
    at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:150) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
    ... 15 more`

MY ADV. CONFIG
http://pastebin.com/t4jcCcDa

I Have STATZ, STATS, & GreifPrevention

**Comment by AgentCortez** [comment]
AUTORANK CONFIG
http://pastebin.com/TRijVv8N

I also have GriefPrevention, Statz, & Stats.

**Comment by Staartvin** [comment]
When does this error occur?

**Comment by AgentCortez** [comment]
I removed stats because Statz does the exact same thing it does.

This happens whenever I execute /ar check

**Comment by Staartvin** [comment]
What group are you in when you perform /ar check? Which group will Autorank check?

**Comment by AgentCortez** [comment]
the very first group 

default;explorer

**Comment by Staartvin** [comment]
You are now running Autorank and Statz but not Stats right? This exact error cannot happen when Stats is not installed.

**Comment by AgentCortez** [comment]
Actually, after i removed Stats, i tested it again, and the same error occurred

**Comment by AgentCortez** [comment]
I also tried deleting all files in Statz and Autorank (Except AdvancedConfig) and reloading it. No luck.

**Comment by AgentCortez** [comment]
I also tried a different configuration in the adv. file:

http://pastebin.com/63NtgCK8

**Comment by AgentCortez** [comment]
Also, here is my PermissionsEx file. Please make sure that the group "default" has the correct perms.

http://pastebin.com/7aZFv9en

**Comment by Staartvin** [comment]
And it still giving you that stack trace?

**Comment by AgentCortez** [comment]
Same stacktrace

**Comment by Staartvin** [comment]
Could you add me on Skype? (Staartvin)

**Comment by AgentCortez** [comment]
sent a request

**Comment by AgentCortez** [comment]
**I Found the issue!**

I put in blocks broken and blocks placed without an ID because I just wanted the amount. Apparently, you can't do that so that's why the /ar check was not working. I tried: 0;1000. ;1000, and 1000. none of them working for just amount.

Basically you can't just have amount blocks broken, you have to have the ID of a block.
