### ISSUE TITLE
Strange error.

### ISSUE THREAD

**Issue by TeeKay1** [Armarr/Autorank-2#389]
Ok so I fixed my original issue, But I have a new one...basically its saying "[23:54:05 ERROR]: [Autorank] There are invalid groups defined in the config!" but its there...and i have run the debug and nothing is coming up...I'm not sure the issue here.

**Comment by TeeKay1** [comment]
Heres another one now...

[22:57:04 WARN]: Exception in thread "Craft Scheduler Thread - 230"
[22:57:04 WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.8.4 generated an exception while executing task 50102
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: me/staartvin/statz/hooks/Dependency
        at me.armar.plugins.autorank.playtimes.Playtimes.getTimeOfPlayer(Playtimes.java:316)
        at me.armar.plugins.autorank.leaderboard.Leaderboard.getSortedPlaytimes(Leaderboard.java:127)
        at me.armar.plugins.autorank.leaderboard.Leaderboard.updateLeaderboard(Leaderboard.java:214)
        at me.armar.plugins.autorank.leaderboard.Leaderboard$4.run(Leaderboard.java:318)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by TeeKay1** [comment]
And another form the MySQL

[22:57:04 INFO]: SQLDataStorage.connect
[22:57:04 INFO]: SQLException: Unknown database 'minecraft'
[22:57:04 INFO]: SQLState: 42000
[22:57:04 INFO]: VendorError: 1049
[22:57:04 ERROR]: [Autorank] Could not connect to localhost:3306
[22:57:04 INFO]: [Autorank DEBUG] Could not connect to MYSQL!
[22:57:05 INFO]: [Autorank DEBUG] Saving all data files...
[22:57:09 WARN]: Exception in thread "Craft Scheduler Thread - 229"
[22:57:09 WARN]: org.apache.commons.lang.UnhandledException: Plugin Autorank v3.8.4 generated an exception while executing task 50100
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at me.armar.plugins.autorank.config.ConfigHandler.getRanks(ConfigHandler.java:99)
        at me.armar.plugins.autorank.rankbuilder.ChangeGroupBuilder.initAdvancedConfig(ChangeGroupBuilder.java:153)
        at me.armar.plugins.autorank.rankbuilder.ChangeGroupBuilder.initialiseChangeGroups(ChangeGroupBuilder.java:52)
        at me.armar.plugins.autorank.rankbuilder.ChangeGroupManager.initialiseFromConfigs(ChangeGroupManager.java:47)
        at me.armar.plugins.autorank.Autorank$1.run(Autorank.java:330)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
