### ISSUE TITLE
Error when running /ar check using block breaker

### ISSUE THREAD

**Issue by ssandiss** [Armarr/Autorank-2#392]
Hey

I've been trying to fix the blockbreaker in /ar check. but I get a console error of this:

`[12:28:11] [Server thread/INFO]: ssandiss issued server command: /ar check
[12:28:11] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ar' in plugin Autorank v3.8.4-Dev-598
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.2.jar:git-Spigot-2486fb7-c74e2a7]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.10.2.jar:git-Spigot-2486fb7-c74e2a7]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[spigot-1.10.2.jar:git-Spigot-2486fb7-c74e2a7]
at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.2.jar:git-Spigot-2486fb7-c74e2a7]
at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.2.jar:git-Spigot-2486fb7-c74e2a7]
at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.2.jar:git-Spigot-2486fb7-c74e2a7]
at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.2.jar:git-Spigot-2486fb7-c74e2a7]
at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-2486fb7-c74e2a7]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-2486fb7-c74e2a7]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-2486fb7-c74e2a7]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-2486fb7-c74e2a7]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-2486fb7-c74e2a7]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-2486fb7-c74e2a7]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
at me.armar.plugins.autorank.playerchecker.requirement.BlocksBrokenRequirement.meetsRequirement(BlocksBrokenRequirement.java:82) ~[?:?]
at me.armar.plugins.autorank.rankbuilder.holders.RequirementsHolder.meetsRequirement(RequirementsHolder.java:79) ~[?:?]
at me.armar.plugins.autorank.commands.CheckCommand.check(CheckCommand.java:143) ~[?:?]
at me.armar.plugins.autorank.commands.CheckCommand.onCommand(CheckCommand.java:295) ~[?:?]
at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:150) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.10.2.jar:git-Spigot-2486fb7-c74e2a7]
... 15 more`

Not sure what's causing it, but the error started after I added Stats.

AdvancedConfig: http://pastebin.com/P7ZK3Mi8

**Comment by Staartvin** [comment]
Please upgrade to latest version of Autorank and Statz.
