### ISSUE TITLE
null org.bukkit.command.CommandException: Unhandled exception executing command 'ar' in plugin Autorank v3.8.5.1-Dev-619

### ISSUE THREAD

**Issue by Defkiller44** [Armarr/Autorank-2#419]
[14:07:37 INFO]: Defkiller44 issued server command: /ar check
[14:07:37 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ar' in plugin Autorank v3.8.5.1-Dev-619
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[divinity.jar:git-Spigot-f9671b8-48b88ed]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[divinity.jar:git-Spigot-f9671b8-48b88ed]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[divinity.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [divinity.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [divinity.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [divinity.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [divinity.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [divinity.jar:git-Spigot-f9671b8-48b88ed]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [divinity.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [divinity.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [divinity.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [divinity.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [divinity.jar:git-Spigot-f9671b8-48b88ed]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
        at me.armar.plugins.autorank.permissions.PermissionsPluginManager.getPrimaryGroup(PermissionsPluginManager.java:92) ~[?:?]
        at me.armar.plugins.autorank.commands.CheckCommand.check(CheckCommand.java:50) ~[?:?]
        at me.armar.plugins.autorank.commands.CheckCommand.onCommand(CheckCommand.java:295) ~[?:?]
        at me.armar.plugins.autorank.commands.manager.CommandsManager.onCommand(CommandsManager.java:150) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[divinity.jar:git-Spigot-f9671b8-48b88ed]
        ... 15 more

Ever since I got this error I could not do /ar check. In-game after doing **/ar check it says, "An internal error occured while performing this command."**
I am running on Stats3, my data is being stored on flatfile. Just a few things if it helps at all. 

This is my AdvancedConfig,   [http://pastebin.com/6p1rzcex](url)

**Comment by Defkiller44** [comment]
Solved this myself. The problem was Stats3. I replaced it with the Statz plugin and the error message went away.

**Comment by Staartvin** [comment]
Good you fixed it yourself! Sorry I couldn't help :(

**Comment by cjburkey01** [comment]
I am still getting this error, I have stats on the latest version, and flatfile
