### ISSUE TITLE
Autorank Error

### ISSUE THREAD

**Issue by dragonzero39** [Armarr/Autorank-2#47]
Hittin a wall here. Any help?

[21:12:10] [Server thread/INFO]: [Autorank] Enabling Autorank v2.8 Beta
[21:12:10] [Server thread/INFO]: [Autorank] Simple config file loaded
[21:12:10] [Server thread/INFO]: [Autorank] Advanced config file loaded
[21:12:10] [Server thread/INFO]: [Autorank] New playerdata.yml file loaded. AR can keep track of player progress now!
[21:12:11] [Server thread/INFO]: [Autorank] Successfully established connection to central.mysql.pytohost.com:3306
[21:12:11] [Server thread/INFO]: [Autorank] Interval check every 0 minutes.
[21:12:11] [Server thread/INFO]: [Autorank] Data file loaded
[21:12:11] [Server thread/INFO]: [Autorank] Essentials was found! AFK integration can be used.
[21:12:11] [Server thread/INFO]: [Autorank] Vault Hooked!
[21:12:11] [Server thread/INFO]: [Autorank] Found Stats plugin: Stats (by Lolmewn)
[21:12:11] [Server thread/ERROR]: Error occurred while enabling Autorank v2.8 Beta (Is it up to date?)
java.lang.NullPointerException
    at me.armar.plugins.autorank.config.ConfigHandler.getRequirements(ConfigHandler.java:49) ~[?:?]
    at me.armar.plugins.autorank.playerchecker.builders.RankChangeBuilder.createFromAdvancedConfig(RankChangeBuilder.java:92) ~[?:?]
    at me.armar.plugins.autorank.playerchecker.PlayerChecker.initialiseFromConfigs(PlayerChecker.java:48) ~[?:?]
    at me.armar.plugins.autorank.Autorank.onEnable(Autorank.java:198) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:250) ~[cbdev.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3022jnks]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:350) [cbdev.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3022jnks]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:389) [cbdev.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3022jnks]
    at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugin(CraftServer.java:439) [cbdev.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3022jnks]
    at org.bukkit.craftbukkit.v1_7_R1.CraftServer.enablePlugins(CraftServer.java:375) [cbdev.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3022jnks]
    at net.minecraft.server.v1_7_R1.MinecraftServer.m(MinecraftServer.java:342) [cbdev.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3022jnks]
    at net.minecraft.server.v1_7_R1.MinecraftServer.g(MinecraftServer.java:319) [cbdev.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3022jnks]
    at net.minecraft.server.v1_7_R1.MinecraftServer.a(MinecraftServer.java:275) [cbdev.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3022jnks]
    at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:175) [cbdev.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3022jnks]
    at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:424) [cbdev.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3022jnks]
    at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [cbdev.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3022jnks]

**Comment by JINXADORE** [comment]
Hey ,

we have a Server and we are Trying to do a Advanced config edit but we fail every time.

We ask around and noone could help us so the Author is the last posibility.

Could you please help and tell us the reason why the config is still Invaild and Groups are not defined ?

 

This is a debug file of Autorank. You should give this to an author or ticket manager of Autorank.
You can go to http://pastebin.com/ and paste this file. Then, give the link and state the problems you're having in a ticket on the Autorank page.

Date created: 2019-07-07 16:33:54

Autorank version: 3.7.2

Server implementation: git-Spigot-1.7.9-R0.2-208-ge0f2e95 (MC: 1.7.10)

Server version: 1.7.10-R0.1-SNAPSHOT

Server warning state: DEFAULT

Ranks defined:

------------------- ChangeGroup debug info ------------------- 
Group: Nomad
- Nomad
- 1 requirements
- 3 results
----------------------------
Group: Vagabond
- Vagabond
- 1 requirements
- 3 results
----------------------------
Group: Drifter
- Drifter
- 1 requirements
- 3 results
----------------------------
Group: Scarab
- Scarab
- 1 requirements
- 3 results
----------------------------
Group: Seeker
- Seeker
- 1 requirements
- 3 results
----------------------------
Group: Dunewalker
- Dunewalker
- 1 requirements
- 3 results
----------------------------
Group: Sandstalker
- Sandstalker
- 1 requirements
- 3 results
----------------------------
Group: Pharaoh
- Pharaoh
- 1 requirements
- 3 results
----------------------------
Group: Inquisitor
- Inquisitor
- 1 requirements
- 3 results
----------------------------

Config used: AdvancedConfig.yml

Using MySQL: false

Java version: 10.0.2

Operating system: Windows 10

OS version: 10.0

OS architecture: amd64

Loaded addons: []

 

 

Thank you !
